### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [55]:
import numpy as np
import random

vector = np.random.rand(10)

A = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]
              ])


print("Матриця A:")
print(A)
print("\nРозмір матриці A:")
print(A.shape)
print("\nВектор-рядок vector:")
print(vector)
print("\nРозмір вектора vector:")
print(vector.shape)

Матриця A:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці A:
(3, 3)

Вектор-рядок v:
[0.36898467 0.50702725 0.41534971 0.13525283 0.59015391 0.87112179
 0.07914631 0.2398888  0.24396414 0.14757819]

Розмір вектора v:
(10,)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [27]:
# 1
result = np.round(v + 10, 2)
print("\nv + 10:")
print(result)

# 2
A_mult_2 = 2 * A
print("\nA * 2:")
print(A_mult_2)

# 3
squared_vector = np.square(v)
print("\nv**2:", squared_vector)



v + 10:
[10.89 10.4  10.72 10.8  10.56 10.31 10.87 10.24 10.18 10.07]

A * 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

v**2: [0.78774807 0.1568771  0.51299323 0.63777387 0.30864937 0.09588208
 0.76002678 0.05840606 0.03104939 0.00513502]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [40]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [51]:
# 1 A * B
print("\nA * B:")
result_matrix = np.dot(B, A)
print(result_matrix)

# 2
print("\nC * result_matrix:")
print(result_matrix.shape, C.shape)
# в результаті буде структура (вектор-масив) 2 х 1
result_matrix_vector = np.dot(result_matrix, C)
print(result_matrix_vector)

# 3
print("\nD * result_matrix:")
# в результаті буде матриця 2 х 2
D_result_matrix = np.dot(D, result_matrix)
print(D_result_matrix)


A * B:
[[0.7281 0.5202]
 [0.2034 0.2846]]

C * result_matrix:
(2, 2) (2, 1)
[[0.5202]
 [0.2846]]

D * result_matrix:
[[0.2034 0.2846]
 [0.7281 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [58]:
# 1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [59]:
# 2
tr_vector = vector.T
vector, vector.shape, tr_vector, tr_vector.shape
# форма не змінилась, бо це одновимірний масив, рядковий ветор

(array([0.36898467, 0.50702725, 0.41534971, 0.13525283, 0.59015391,
        0.87112179, 0.07914631, 0.2398888 , 0.24396414, 0.14757819]),
 (10,),
 array([0.36898467, 0.50702725, 0.41534971, 0.13525283, 0.59015391,
        0.87112179, 0.07914631, 0.2398888 , 0.24396414, 0.14757819]),
 (10,))

In [67]:
# 3
column_vector = np.expand_dims(vector, axis = 1)
column_vector, column_vector.shape
# форма вектора змінилась, став вектор-стовпець (двовимірний масив)

(array([[0.36898467],
        [0.50702725],
        [0.41534971],
        [0.13525283],
        [0.59015391],
        [0.87112179],
        [0.07914631],
        [0.2398888 ],
        [0.24396414],
        [0.14757819]]),
 (10, 1))

In [66]:
# 4
tr_column_vector = column_vector.T
tr_column_vector, tr_column_vector.shape
# змінилась форма

(array([[0.36898467, 0.50702725, 0.41534971, 0.13525283, 0.59015391,
         0.87112179, 0.07914631, 0.2398888 , 0.24396414, 0.14757819]]),
 (1, 10))